apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    name: flask-pod
    app: web-app-1
spec:
  containers:
    - name: flask
      image: devnetvn/webapp-1
      ports:
        - containerPort: 5000