apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    name: flask-service
    app: web-app-1
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    name: flask-pod
    app: web-app-1

  
