apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    name: mongo-pod
    app: web-app-1
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017