apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
    app: web-app-1
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-pod
    app: web-app-1