apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: web-app-1
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "cisco123"
        - name: MYSQL_DATABASE
          value: "devcor2023"